### ISSUE TITLE
[Public API] Get Employee details by ID

### ISSUE THREAD

**Issue by lymychp** [Nebo15/ehealth.api#332]
Implement the subj. service according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employee-details)
[Basic logic](https://edenlab.atlassian.net/wiki/display/EH/IL.Employee+details)

**Comment by mmiliaieva** [comment]
Missing object doctor in response, if "employee_type": "DOCTOR"
Excess parameters in response:
$.data.party
$.data.legal_entity

**Comment by PavelVesnin** [comment]
Spec contains `$.data.party` and `$data.legal_entity` fields

**Comment by mmiliaieva** [comment]
@PavelVesnin 
1. Delete parameters from response
$.data.updated_by
$.data.party_id
$.data.legal_entity_id
$.data.inserted_by
$.data.division_id
$.data.party.updated_by
$.data.party.inserted_by
$.data.legal_entity.updated_by
$.data.legal_entity.updated_at
$.data.legal_entity.phones
$.data.legal_entity.medical_service_provider
$.data.legal_entity.kveds
$.data.legal_entity.is_active
$.data.legal_entity.inserted_by
$.data.legal_entity.inserted_at
$.data.legal_entity.email
$.data.legal_entity.created_by_mis_client_id
$.data.legal_entity.addresses
2. Missing parameters
$.data.party.email
3. Division should be abject, instead of array

**Comment by PavelVesnin** [comment]
@mmiliaieva object `party ` doen't contain `email` field - [see](https://github.com/Nebo15/ehealth.api/blob/master/specs/database_schema/prm.erd#L163)

**Comment by mmiliaieva** [comment]
Approved, postman tests passed
