### ISSUE TITLE
Deploy PreProd env

### ISSUE THREAD

**Issue by warehousman** [Nebo15/ehealth.api#369]
So MIS can test exact the same versions existing on production without impact of newly developed functionality

**Comment by pzhuk** [comment]
I propose to deploy preprod under same domain as prod, having SSL termination on CF without any strict SSL backend.

**Comment by pzhuk** [comment]
предпрод:
домен: ehealth-ukraine.org  (суфікси в субдомені "preprod-")
сертифікат: не потрібен, термінація SSL на Cloudflare

**Comment by pzhuk** [comment]
@AndrewDryga lmk if anything else required

**Comment by AndrewDryga** [comment]
@pzhuk Then we are missing one of the main purposes for preprod - testing configuration.

I guess you already received this message, but I'll quote it here:
> One of the main goals for preprod environment is testing release with exactly the same code and configuration. And even trough code doesn’t care on which domain it lives, for configuration it is important to emulate exactly the same project structure.
> 
> - I will be really bad to add production SSL certificate to a cluster that is hosted in development account where access control is very permissive, also I will be bad for us to host preprod on a production account since we will need to give developers access to the cluster which will make IAM policies error-prone.
So to keep everything in a separate account/cluster and with the same structure, we need another certificate that is “safe to loose”. Preferably it should be issued on another domain, rather that ehealth-ukraine.org, otherwise, it can be used to MITM-attack our production servers.
> 
> - Using CloudFlare SSL is not an option because it will change the structure and we will test code, but we won’t be able to test that configuration itself has bugs. For example, we won’t be able to test functionality relative to the SSL termination itself.
>
> - Using self-signed certificate will make our API consumers code error-prone, they will need to disable SSL verification in their code and this change can occasionally go into the live system.
